### PR TITLE
Admin dashboard fix

### LINKED ISSUE #212: admin dashboard
everything on one page

### PR DESCRIPTION
**Pull request by aziobrow**
Closes #212

Description of Changes:
Put everything on admin show page, added dropdown filter for orders by status. Needs styling work for sure. Removed admin order index where this functionality formerly lived. 

@anlewi5, @josimccllelan, @aziobrow

### CODE REVIEW

File: app/models/order.rb [hunk 1]
```diff
@@ -24,4 +24,12 @@ def save_purchaser_name
     self.purchaser_name ||= user && user.username
   end
 
+  def self.parse_params(params)
```
Comment (anlewis) [inline app/models/order.rb:27]: This is a weird method name to me. Maybe something like sort_by_status instead? It's unclear from the name what the method does.
